apiVersion: v1
kind: ReplicationController
metadata:
  name: allocator
  labels:
    app: allocator 
spec:
  replicas: 1
  selector:
    name: allocator 
  template:
    metadata:
      labels:
        name: allocator 
    spec:
      containers:
      - name: allocator 
        image: 954636985443.dkr.ecr.us-west-2.amazonaws.com/pipelineai/allocator:1.5.0
        imagePullPolicy: "Never"
        env:
        ports:
        - containerPort: 5070 
