apiVersion: v1
kind: Service
metadata:
  name: allocator 
  labels:
spec:
  type: NodePort 
  ports:
  - name: allocator 
    port: 80
    targetPort: 5070
    nodePort: 30050
  selector:
    name: allocator 
