apiVersion: v1
kind: ReplicationController
metadata:
  name: allocator
  labels:
    app: allocator 
spec:
  replicas: 1
  selector:
    name: allocator 
  template:
    metadata:
      labels:
        name: allocator 
    spec:
      containers:
      - name: allocator 
        image: docker.io/pipelineai/allocator:master
        imagePullPolicy: "Always"
        env:
        ports:
        - containerPort: 5070 
