apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notebook-community-gpu
  labels:
    app: notebook-community-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook-community-gpu
  template:
    metadata:
      labels:
        app: notebook-community-gpu
    spec:
      containers:
      - name: notebook-community-gpu
        image: docker.io/pipelineai/notebook-gpu:1.5.0
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
            memory: 12000Mi
          requests:
            memory: 12000Mi
        imagePullPolicy: "Always"
        volumeMounts:
        - mountPath: /usr/local/cuda
          name: cuda
          readOnly: true
        - mountPath: /rootfs/usr/lib
          name: rootfs-usr-lib
          readOnly: true
        - mountPath: /root/notebooks
          name: notebooks-volume
        - mountPath: /root/models
          name: models-volume
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: SPARK_MASTER
          value: spark://spark-master-2-1-0:7077
        - name: SPARK_SUBMIT_ARGS
          value: ""
        - name: JUPYTERHUB_AUTHENTICATOR
          value: dummyauthenticator.DummyAuthenticator
        - name: AUTH0_SUBDOMAIN
          value: ""
        - name: OAUTH_CALLBACK_URL
          value: ""
        - name: OAUTH_CLIENT_ID
          value: ""
        - name: OAUTH_CLIENT_SECRET
          value: ""
        - name: GITHUB_OAUTH_CLIENT_ID
          value: ""
        - name: GITHUB_OAUTH_CLIENT_SECRET
          value: ""
#          valueFrom:
#            secretKeyRef:
#              name: oauth
#              key: OAUTH_CLIENT_ID
#        - name: OAUTH_CLIENT_SECRET
#          valueFrom:
#            secretKeyRef:
#              name: oauth
#              key: OAUTH_CLIENT_SECRET
#        - name: GITHUB_OAUTH_CLIENT_ID
#          valueFrom:
#            secretKeyRef:
#              name: github-oauth
#              key: GITHUB_OAUTH_CLIENT_ID
#        - name: GITHUB_OAUTH_CLIENT_SECRET
#          valueFrom:
#            secretKeyRef:
#              name: github-oauth
#              key: GITHUB_OAUTH_CLIENT_SECRET
        ports:
        - containerPort: 6006
        - containerPort: 8754
        - containerPort: 8755
        - containerPort: 5000
        - containerPort: 54321
      volumes:
      - hostPath:
          path: /usr/local/cuda
        name: cuda
      - hostPath:
          path: /usr/lib
        name: rootfs-usr-lib
      - gitRepo:
          repository: "https://github.com/PipelineAI/notebooks.git"
          revision: "master"
        name: notebooks-volume
      - gitRepo:
          repository: "https://github.com/PipelineAI/models.git"
          revision: "master"
        name: models-volume
